resize_shape: [256, 256]
targets: ['Fire_Images']
model_file_paths: ["cnn_classifier_params.h5", "cnn_classifier_layers.json"]
base_model_url: "https://github.com/UPstartDeveloper/Fire-Detection-API/releases/download/v0.0.4"
model_sha256: "26f32ae0666bbb83e11968935db0ec2ab06623d1"
